### PR TITLE
Added H265

### PR DESCRIPTION
**Pull request by diegonunes4**
It's just missing the IS-04 parameters, which ones do you think should be used? @garethsb
Also should I make the PR to the master branch or the video h264?

### CODE REVIEW

**Comment by garethsb** [comment]
You seem to have merged your H.264 code _and_ my approach to it (_nmos/video_h264.{cpp,h}_). I don't think we want both. What do you think to the format-specific header/source file approach? Can you also use it for H.265?

**Comment by diegonunes4** [comment]
Ok, I will then extract the code and add it to another branch!
I agree with the header/source file, I will use it.

**Comment by garethsb** [comment]
> which ones do you think should be used?

I previously documented a preliminary look at it here: https://github.com/sony/nmos-cpp/issues/213#issuecomment-979016210

Reading the IANA media type registration, linked there, I agree profile-id and level-id may be useful. I think all bit-fields in interop-constraints is covered by existing IS-04 Flow parameters however?

**Comment by garethsb** [comment]
I think the best link for the RFC is https://tools.ietf.org/html/rfc7798

**Comment by garethsb** [comment]
This will also make us think about whether we should define common reusable `profile_level` (or separate `profile` and `level`) for the IS-04 Flow, which MPEG 2, AVC, HEVC, VP9, etc. can all use,  or whether each format has to have its own similar but different parameters.

**Comment by garethsb** [comment]
> Ok, I will then extract the code and add it to another branch!
> I agree with the header/source file, I will use it.

Thanks, that'd be great. See if you think the pattern I've used for _nmos/video_h264.{h,cpp}_ can be entirely repeated for H.265 and do it as a separate branch also starting from _master_.

**Comment by garethsb** [comment]
Closing now we have #7.

**Pull request closed without merging**
